### ISSUE TITLE
Latest Windows release hangs

### ISSUE THREAD

**Issue by matkuki** [mneuroth/SciTEQt#4]
Hi,

Great project 👍
I tried the latest release (all three `.exe` installers) and when `SciteQt` window opens, it's blank, hangs, and uses one CPU core to the max.
I'm on Windows 10 x64.

Regards

**Comment by mneuroth** [comment]
Hi,

thank you for your feedback and sorry for the late reply. I could verify your problem and I fixed it and released a [new version ](https://github.com/mneuroth/SciTEQt/releases/tag/v0.99.19_release_beta). could you please try this new release?
Regards

  Michael

**Comment by matkuki** [comment]
Confirming that it works, thank you 👍
